apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: my-fullstack-app
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: my-fullstack-backend:latest
        imagePullPolicy: IfNotPresent # Use local image if available
        ports:
        - containerPort: 8000
        env:
        - name: CORS_ORIGINS
          value: "http://localhost:30300"
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
