-- add-image-alt.lua
-- Fixes "Package keyval Error: alt undefined" when using pandoc 3.x to
-- produce PDF output from documents that contain embedded images (e.g.
-- those generated by mermaid-filter).
--
-- Pandoc 3.x's LaTeX writer injects alt={...} into \includegraphics
-- during the write phase (after filters), so we must define 'alt' as a
-- no-op key for the graphicx (Gin) key family at the LaTeX level.
--
-- This function appends a raw LaTeX block to the document's
-- header-includes metadata, declaring 'alt' as a no-op key for the
-- Gin (graphicx) key family so that LaTeX silently ignores it.
--
-- Usage:
--   pandoc input.md --filter mermaid-filter --lua-filter add-image-alt.lua -o output.pdf

function Meta(meta)
  local header_includes = meta['header-includes'] or pandoc.MetaList({})
  header_includes[#header_includes + 1] = pandoc.MetaBlocks({
    pandoc.RawBlock('latex', '\\makeatletter\\define@key{Gin}{alt}{}\\makeatother')
  })
  meta['header-includes'] = header_includes
  return meta
end
